const express = require("express");
const router = express.Router();

router.use("/", require("./v1/auth.route"));
router.use("/user", require("./v1/user.route"));
router.use("/review", require("./v1/review.route"));
router.use("/role", require("./v1/role.route"));
router.use("/profile", require("./v1/profile.route"));
router.use("/job", require("./v1/job.route"));
router.use("/job-type/", require("./v1/jobType.route"));
router.use("/event/", require("./v1/event.route"));
router.use("/post/", require("./v1/post.route"));
router.use("/page/", require("./v1/page.route"));
router.use("/category/", require("./v1/category.route"));
router.use("/dashboard", require("./v1/dashboard.route"));
router.use("/site-settings", require("./v1/siteSetting.route"));
router.use("/email-templates", require("./v1/emailTemplate.route"));
router.use("/services", require("./v1/service.route"));
router.use("/plans", require("./v1/plan.route"));
router.use("/countries", require("./v1/country.route"));
router.use("/cities", require("./v1/city.route"));
router.use("/faq", require("./v1/faq.route"));
router.use("/party-Role", require("./v1/partyRole.route"));
router.use("/booking", require("./v1/booking.route"));
router.use("/event-types", require("./v1/eventTypes.route"));
router.use("/timezones", require("./v1/timzones.route"));
router.use("/social", require("./v1/socialMedias.route"));
router.use("/chat", require("./v1/chat.route"));
router.use("/info", require("./v1/info.route"));
router.use("/enquiry", require("./v1/enquiry.route"));
router.use("/transaction", require("./v1/transaction.route"));
module.exports = router;
